// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9i-aSWOjmZbXo0Uot9iL5iJ-F5sdlbJ8',
    appId: '1:292442788801:web:5d78a1c32d0f106c3e9540',
    messagingSenderId: '292442788801',
    projectId: 'fooddeliverytute-fae88',
    authDomain: 'fooddeliverytute-fae88.firebaseapp.com',
    storageBucket: 'fooddeliverytute-fae88.firebasestorage.app',
    measurementId: 'G-3DZKCXYNLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHC4GIr7j1ImmRcZjF7xPlK92oK3G9MAk',
    appId: '1:292442788801:android:fe5f605dc980a4bc3e9540',
    messagingSenderId: '292442788801',
    projectId: 'fooddeliverytute-fae88',
    storageBucket: 'fooddeliverytute-fae88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFxlCyqYWHO18L80n3I4Lk2-FJbErf718',
    appId: '1:292442788801:ios:a4291f050770a5683e9540',
    messagingSenderId: '292442788801',
    projectId: 'fooddeliverytute-fae88',
    storageBucket: 'fooddeliverytute-fae88.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFxlCyqYWHO18L80n3I4Lk2-FJbErf718',
    appId: '1:292442788801:ios:a4291f050770a5683e9540',
    messagingSenderId: '292442788801',
    projectId: 'fooddeliverytute-fae88',
    storageBucket: 'fooddeliverytute-fae88.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9i-aSWOjmZbXo0Uot9iL5iJ-F5sdlbJ8',
    appId: '1:292442788801:web:5a94a29030daae9b3e9540',
    messagingSenderId: '292442788801',
    projectId: 'fooddeliverytute-fae88',
    authDomain: 'fooddeliverytute-fae88.firebaseapp.com',
    storageBucket: 'fooddeliverytute-fae88.firebasestorage.app',
    measurementId: 'G-H7X5SLQL1L',
  );
}
